spring:
  application:
    name: child-tracking-system

jwt:
  secret-key: A:DIFJ:LJGFENPIDOPVHGA:LEKFNSKASLDMF:ADSISFJGDSCBO:IJNELFO:SIDJSD!@#
  access-token:
    expiration-time: 600000000

swagger:
  server-url: http://localhost:8080

#dd